name: "Pull Request Build"
on:
  - pull_request
jobs:
  build:
    name: JVM build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: |
          mvn -V -B -s .github/mvn-settings.xml clean verify
      - name: Zip Artifacts
        run: |
          zip -R artifacts.zip '*-reports/*'
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts.zip